### Variables
@baseUrl = http://localhost:8000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTQ5ODcxLCJpYXQiOjE3MzgwNjM0NzEsImp0aSI6IjdmZDQwNzczNTc0YjQ0NzlhYzgyNjMyNzczN2I1Y2ZkIiwidXNlcl9pZCI6M30.saayefxiTguFE_j1nmj4aIE8WCsoiQbWyysGl3eYtUU
@storeOwnerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTQ5ODMwLCJpYXQiOjE3MzgwNjM0MzAsImp0aSI6IjMyZWYwZDlmYzMyNzRlYTRiOTAzOTk0ZDhmYzllNzFlIiwidXNlcl9pZCI6MTF9.LJsvVbXoHmRpH2qIylzJNOVpjIyrx85R8A_YAFoGtdU
@regularUserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTQ5ODg0LCJpYXQiOjE3MzgwNjM0ODQsImp0aSI6IjNiYTAwZmNkNjVkNDRjNmE4YjZmZTM1YWRlOGViNTFjIiwidXNlcl9pZCI6MX0.fLXourCRTAn5BFMLt1PXwdQz8dqRhvj91CpwEkdL3ac

### Obtain JWT Token (Login)
#!Customer
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "john_doe",
  "password": "password123"
}
###

###
#!Store Owner
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "lucas_perez",
  "password": "password123"
}
###
#!ADMIN
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "alice_johnson",
  "password": "password123"
}


###! 1. Admin Operations

# Get all products as admin
GET {{baseUrl}}/products/
Authorization: Bearer {{adminToken}}

### Create a product as admin (auto-approved)

POST {{baseUrl}}/products/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Admin Test Product",
    "description": "Admin Test Product Description",
    "price": 99.99,
    "stock": 10,
    "brand_id": 2,
    "category_ids": [3, 2],
    "store_id": 2
}
### Create a brands as admin

POST {{baseUrl}}/brands/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "admin brand"

}


### Create a category as admin
POST {{baseUrl}}/categories/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "admin categories"

}


### Update a product as admin (auto-approved)

PUT {{baseUrl}}/products/20/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "admin 0000",
    "description": "A test product description",
    "price": 9.25,
    "stock": 1,
    "brand_id": 3,
    "category_ids": [2],
    "store_id": 2
}

### Get Product by ID
GET {{baseUrl}}/products/20/

###? A review as Customer
POST {{baseUrl}}/products/20/add_review/
Authorization: Bearer {{regularUserToken}}
Content-Type: application/json

{
    "rating": 2,
    "comment": "Excellent product, highly recommended!"
}


