### Variables
@baseUrl = http://localhost:8000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTYyMDAxLCJpYXQiOjE3MzgwNzU2MDEsImp0aSI6IjhjOTdkMGIzMDM3NjRmMTc4MjYzODQ2MDUwNjEyMGFlIiwidXNlcl9pZCI6M30.VyuZtxRGa1YhD71o_MyHkADA3Jv7nmXOEHqgWyVIV_s
@storeOwnerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTQ5ODMwLCJpYXQiOjE3MzgwNjM0MzAsImp0aSI6IjMyZWYwZDlmYzMyNzRlYTRiOTAzOTk0ZDhmYzllNzFlIiwidXNlcl9pZCI6MTF9.LJsvVbXoHmRpH2qIylzJNOVpjIyrx85R8A_YAFoGtdU
@regularUserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTYxOTg4LCJpYXQiOjE3MzgwNzU1ODgsImp0aSI6IjM0YzQ2ZDUxOTM3YTQ0MmJiNzZkMDhmNjIxMDU0ZTg1IiwidXNlcl9pZCI6MX0.rAiVPrzCZblFy-JHli92xlIkFyVST3aUhFTVJBK9FhM

### Obtain JWT Token (Login)
#!Customer
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "john_doe",
  "password": "password123"
}
###

###
#!Store Owner
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "lucas_perez",
  "password": "password123"
}
###
#!ADMIN
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "alice_johnson",
  "password": "password123"
}


###! 1. Admin Operations

# Get all products as admin
GET {{baseUrl}}/products/
Authorization: Bearer {{adminToken}}

### Create a product as admin (auto-approved)

POST {{baseUrl}}/products/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Admin Test Product 01",
    "description": "Admin Test Product Description",
    "price": 9.99,
    "stock": 1,
    "brand_id": 2,
    "category_ids": [3, 2],
    "store_id": 2
}
### Create a brands as admin

POST {{baseUrl}}/brands/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "admin brand"

}


### Create a category as admin
POST {{baseUrl}}/categories/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "admin categories"

}


### Update a product as admin (auto-approved)

PUT {{baseUrl}}/products/20/
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "updayed ",
    "description": "A test product description",
    "price": 9.25,
    "stock": 1,
    "brand_id": 3,
    "category_ids": [2],
    "store_id": 2
}

### Get Product by ID
GET {{baseUrl}}/products/20/

###? A review as Customer
POST {{baseUrl}}/products/20/add_review/
Authorization: Bearer {{regularUserToken}}
Content-Type: application/json

{
    "rating": 2,
    "comment": "Excellent product, highly recommended!"
}


### Add Product to Cart (replace <product_id> with actual ID)
POST {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Bearer {{regularUserToken}}

{
    "product": 1,
    "quantity": 2
}

### Add Same Product Again (quantity should increase to 4)
POST {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Bearer {{regularUserToken}}

{
    "product": 1,
    "quantity":1
}

### Add Different Product
POST {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Bearer {{regularUserToken}}

{
    "product": 2,
    "quantity": 3
}

### Get Cart Contents
GET {{baseUrl}}/cart/
Authorization: Bearer {{regularUserToken}}

### Remove Cart Item (replace <item_id> with actual ID)
DELETE {{baseUrl}}/cart/66/
Authorization: Bearer {{regularUserToken}}



### Create Order from Cart
POST {{baseUrl}}/orders/
Content-Type: application/json
Authorization: Bearer {{regularUserToken}}


{
    "from_cart": true
}


### Create Direct Order
POST {{baseUrl}}/orders/
Content-Type: application/json
Authorization: Bearer {{regularUserToken}}

{
    "product_id": 12,
    "quantity": 2
}


### Get Orders List
GET {{baseUrl}}/orders/
Authorization: Bearer {{regularUserToken}}




